//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Druzyna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Druzyna()
        {
            this.Ogloszenia = new HashSet<Ogloszenia>();
            this.Zawodnik = new HashSet<Zawodnik>();
        }
    
        public int id_druzyna { get; set; }
        public string nazwa { get; set; }
        public int id_trener { get; set; }
        public int id_masazysta { get; set; }
        public int id_kierownik { get; set; }
    
        public virtual Kierownik Kierownik { get; set; }
        public virtual Masazysta Masazysta { get; set; }
        public virtual Trener Trener { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogloszenia> Ogloszenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zawodnik> Zawodnik { get; set; }
    }
}
