//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zawodnik
    {
        public int id_zawodnik { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int id_pozycja { get; set; }
        public int id_druzyna { get; set; }
    
        public virtual Druzyna Druzyna { get; set; }
        public virtual Pozycja Pozycja { get; set; }
    }
}
